defmodule Spectre.Instance.State do
  @moduledoc false

  alias Spectre.AgentRef
  alias Spectre.Instance.Canonical
  alias Spectre.Instance.Ref
  alias Spectre.Result
  alias Spectre.Run
  alias Spectre.State, as: AgentState
  alias Spectre.Subject

  # The private owner state mirrors independent OTP resources and canonical sections.
  # credo:disable-for-next-line Credo.Check.Warning.StructFieldAmount
  defstruct [
    :agent,
    :agent_ref,
    :subject,
    :ref,
    :state,
    :canonical,
    :activation,
    :definition_store,
    :owner,
    :owner_lease,
    :last_result,
    :active,
    :state_lock,
    :idle_timeout,
    :idle_timer,
    :base_opts,
    :max_runs,
    :max_tombstones,
    :generation,
    :runner_supervisor,
    :stack_runtime,
    :max_operation_runners,
    :max_stream_sessions,
    :stream_registry,
    :stream_capacity,
    :checkpoint_store,
    :checkpoint_mode,
    :checkpoint_persisted,
    :checkpoint_reconciliation,
    :checkpoint_reconcile_inflight,
    :receipt_mode,
    :receipt_sink,
    :max_receipt_outbox,
    :registry,
    :registry_monitor,
    scheduled: false,
    operation_scheduled: false,
    conversations: %{},
    runs: %{},
    ready: :queue.new(),
    queued: MapSet.new(),
    entries: %{},
    callers: %{},
    invocations: %{},
    workers: %{},
    completed: :queue.new(),
    terminal_recorded: MapSet.new(),
    tombstones: %{},
    tombstone_order: :queue.new(),
    operation_ready: :queue.new(),
    operation_queued: MapSet.new(),
    operation_runners: %{},
    operation_monitors: %{},
    operation_attempt_timers: %{},
    operation_timers: %{},
    operation_progress_clock: %{},
    operation_liveness_clock: %{},
    inference_liveness_clock: %{},
    inference_checkpoint_clock: %{},
    inference_progress_commit_clock: %{},
    inference_attempt_timers: %{},
    stream_sessions: %{},
    stream_monitors: %{},
    stream_reservations: %{},
    checkpoint_revision: 0,
    checkpoint_inflight: nil,
    checkpoint_pending: nil,
    checkpoint_error: nil,
    checkpoint_waiters: [],
    receipt_staging: %{},
    receipt_deliveries: %{},
    receipt_retry_timers: %{},
    receipt_resumes: %{},
    durability_resumes: %{},
    receipt_recovery_deferred: false,
    idle_generation: 0
  ]

  @type t :: %__MODULE__{
          agent: module(),
          agent_ref: AgentRef.t(),
          subject: Subject.t(),
          ref: Ref.t(),
          state: AgentState.t(),
          canonical: Canonical.t(),
          activation: Spectre.Instance.Activation.t() | nil,
          definition_store: Spectre.Definition.Store.config() | nil,
          owner: Spectre.Instance.Owner.config(),
          owner_lease: Spectre.Instance.Owner.Lease.t(),
          last_result: Result.t() | nil,
          active: map() | nil,
          state_lock: map() | nil,
          idle_timeout: timeout() | false | nil,
          idle_timer: reference() | nil,
          base_opts: keyword(),
          max_runs: pos_integer(),
          max_tombstones: non_neg_integer(),
          generation: String.t(),
          runner_supervisor: GenServer.server(),
          stack_runtime: nil | atom() | {:via, module(), term()},
          max_operation_runners: pos_integer(),
          max_stream_sessions: pos_integer(),
          stream_registry: atom(),
          stream_capacity: GenServer.server(),
          checkpoint_store: nil | {module(), keyword()},
          checkpoint_mode: :async | :manual,
          checkpoint_persisted: Canonical.t() | nil,
          checkpoint_reconciliation: map() | nil,
          checkpoint_reconcile_inflight: map() | nil,
          receipt_mode: :disabled | :observational | :required,
          receipt_sink: Spectre.Receipt.Sink.normalized(),
          max_receipt_outbox: pos_integer(),
          registry: atom(),
          registry_monitor: reference() | nil,
          scheduled: boolean(),
          operation_scheduled: boolean(),
          conversations: %{optional(String.t()) => map()},
          runs: %{optional(String.t()) => Run.t()},
          ready: :queue.queue(String.t()),
          queued: MapSet.t(String.t()),
          entries: %{optional(String.t()) => map()},
          callers: %{optional(String.t()) => GenServer.from()},
          invocations: %{optional(String.t()) => map()},
          workers: %{optional(pid()) => map()},
          completed: :queue.queue(String.t()),
          terminal_recorded: MapSet.t(String.t()),
          tombstones: %{optional(String.t()) => map()},
          tombstone_order: :queue.queue(String.t()),
          operation_ready: :queue.queue({atom(), String.t()}),
          operation_queued: MapSet.t({atom(), String.t()}),
          operation_runners: %{optional(String.t()) => map()},
          operation_monitors: %{optional(pid()) => String.t()},
          operation_attempt_timers: %{optional(String.t()) => map()},
          operation_timers: %{optional(String.t()) => map()},
          operation_progress_clock: %{optional(String.t()) => non_neg_integer()},
          operation_liveness_clock: %{optional(String.t()) => map()},
          inference_liveness_clock: %{optional(String.t()) => map()},
          inference_checkpoint_clock: %{optional(String.t()) => non_neg_integer()},
          inference_progress_commit_clock: %{optional(String.t()) => non_neg_integer()},
          inference_attempt_timers: %{optional(String.t()) => map()},
          stream_sessions: %{optional(String.t()) => map()},
          stream_monitors: %{optional(pid()) => String.t()},
          stream_reservations: %{optional(String.t()) => term()},
          checkpoint_revision: non_neg_integer(),
          checkpoint_inflight: map() | nil,
          checkpoint_pending: Canonical.t() | nil,
          checkpoint_error: term(),
          checkpoint_waiters: [{GenServer.from(), non_neg_integer()}],
          receipt_staging: %{optional(String.t()) => map()},
          receipt_deliveries: %{optional(String.t()) => map()},
          receipt_retry_timers: %{optional(String.t()) => reference()},
          receipt_resumes: %{optional(String.t()) => term()},
          durability_resumes: %{optional(non_neg_integer()) => [term()]},
          receipt_recovery_deferred: boolean(),
          idle_generation: non_neg_integer()
        }
end
